#Docs: https://prometheus.io/docs/alerting/configuration/

templates: 
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: team-hclc-slack

receivers:
- name: 'team-hclc-slack'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: 'alerts'