# Documentation: https://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 5s

rule_files:
  - "alerts.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'uuid-generation'
    metrics_path: '/uuid-generation-performance/resources/metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['wildfly-configured:8080']